http {
    upstream api {
        server api-01:5000;
        server api-02:5001;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }
}