export enum ServiceCategory {
  BELEZA_E_ESTÉTICA = 'BELEZA & ESTÉTICA',
  REPARAÇÕES_E_MANUTENÇÃO = 'REPARAÇÕES & MANUTENÇÃO',
  SAÚDE_E_BEM_ESTAR = 'SAÚDE & BEM-ESTAR',
  EDUCAÇÃO_E_FORMAÇÃO = 'EDUCAÇÃO & FORMAÇÃO',
  TECNOLOGIA = 'TECNOLOGIA',
  EVENTOS_E_ENTRETENIMENTO = 'EVENTOS & ENTRETENIMENTO',
  LIMPEZA = 'LIMPEZA',
  TRANSPORTE = 'TRANSPORTE',
  FOTOGRAFIA = 'FOTOGRAFIA',
  DESIGN = 'DESIGN',
}
